name: Deploy to S3

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the 'main' branch

jobs:
  deploy-to-s3:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Deploy to S3
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete --exclude '.git/*'  # Remove the `--acl` flag and exclude `.git` files
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}  # S3 bucket name (set this as a repository secret)
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # AWS Access Key ID (set this as a repository secret)
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS Secret Access Key (set this as a repository secret)
          AWS_REGION: 'us-east-1'  # Replace with your S3 bucket's region
          SOURCE_DIR: 'html-website-templates/Animated Landing Page Website Template'  # Point to the directory containing the files to upload
